/* Table of Events */

CREATE TABLE IF NOT EXISTS Events (
	EventID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	EventName VARCHAR(100) NULL,
	EventLocation VARCHAR(100) NULL,
	StartDate DATE NULL,
	EndDate DATE NULL,
	CurrentEvent BIT NULL
);