/* Table of Matches */

CREATE TABLE IF NOT EXISTS Matches (
	MatchID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	EventID INT NOT NULL,
	MatchNo INT NULL,
	MatchNoTag INT NULL,
	RedTeam1 VARCHAR(5) NULL,
	RedTeam2 VARCHAR(5) NULL,
	RedTeam3 VARCHAR(5) NULL,
	BlueTeam1 VARCHAR(5) NULL,
	BlueTeam2 VARCHAR(5) NULL,
	BlueTeam3 VARCHAR(5) NULL,
	MatchVideo VARCHAR(1024) NULL,
	Comments VARCHAR(4096) NULL
);