/* Word Cloud */

CREATE TABLE IF NOT EXISTS WordCloud
(
	EventID INT NOT NULL,
	MatchID INT NOT NULL,
	MatchScoutingID INT NOT NULL PRIMARY KEY,
	Seq INT NULL PRIMARY KEY, 
	Team VARCHAR(10) NULL,	
	WordID INT NOT NULL
);